# Generated by Django 5.1.7 on 2026-09-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('email', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='邮箱')),
                ('password', models.CharField(max_length=120, verbose_name='密码')),
                ('role', models.CharField(choices=[('guest', '住客'), ('manager', '管理员')], max_length=20, verbose_name='角色')),
                ('nickname', models.CharField(max_length=80, verbose_name='昵称')),
            ],
            options={
                'verbose_name': '前台账号',
                'verbose_name_plural': '前台账号',
            },
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('email', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='邮箱')),
                ('nickname', models.CharField(max_length=80, verbose_name='昵称')),
                ('preference_json', models.TextField(blank=True, null=True, verbose_name='偏好 JSON')),
                ('portrait_json', models.TextField(blank=True, null=True, verbose_name='画像 JSON')),
                ('updated_at', models.CharField(blank=True, max_length=40, null=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '住客画像',
                'verbose_name_plural': '住客画像',
            },
        ),
        migrations.CreateModel(
            name='HotelMeta',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('simulating', models.BooleanField(default=True, verbose_name='仿真运行中')),
                ('trend_json', models.TextField(default='[]', verbose_name='趋势 JSON')),
            ],
            options={
                'verbose_name': '仿真状态',
                'verbose_name_plural': '仿真状态',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.CharField(max_length=8, primary_key=True, serialize=False, verbose_name='房号')),
                ('floor', models.IntegerField(verbose_name='楼层')),
                ('name', models.CharField(max_length=40, verbose_name='名称')),
                ('occupied', models.BooleanField(default=False, verbose_name='在住')),
                ('guest_email', models.CharField(blank=True, max_length=120, null=True, verbose_name='住客邮箱')),
                ('scene_applied', models.BooleanField(default=False, verbose_name='场景已应用')),
                ('env_json', models.TextField(verbose_name='环境 JSON')),
                ('devices_json', models.TextField(verbose_name='设备 JSON')),
                ('history_json', models.TextField(verbose_name='温度历史 JSON')),
            ],
            options={
                'verbose_name': '客房',
                'verbose_name_plural': '客房',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SessionToken',
            fields=[
                ('token', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '登录令牌',
                'verbose_name_plural': '登录令牌',
            },
        ),
    ]
