# Generated by Django 5.1.7 on 2026-09-05 11:04

import json

import django.db.models.deletion
from django.db import migrations, models
from django.utils import timezone


ISSUE_LABEL = {
    "insomnia": "失眠",
    "light-sleeper": "易醒",
    "snoring": "打鼾",
    "allergy": "过敏",
}


def backfill_intake(apps, schema_editor):
    Guest = apps.get_model("hotel", "Guest")
    SleepPreferenceRecord = apps.get_model("hotel", "SleepPreferenceRecord")
    GuestUpload = apps.get_model("hotel", "GuestUpload")
    GuestServiceChoice = apps.get_model("hotel", "GuestServiceChoice")
    now = timezone.now()
    for guest in Guest.objects.all():
        pref = {}
        portrait = {}
        if guest.preference_json:
            try:
                pref = json.loads(guest.preference_json)
            except json.JSONDecodeError:
                pref = {}
        if guest.portrait_json:
            try:
                portrait = json.loads(guest.portrait_json)
            except json.JSONDecodeError:
                portrait = {}
        scene_name = portrait.get("sceneName") or ""
        guest.stay_scene = pref.get("stayScene") or ""
        guest.gender = pref.get("gender") or ""
        guest.scene_title = scene_name
        if pref:
            guest.preference_at = now
            SleepPreferenceRecord.objects.update_or_create(
                guest=guest,
                defaults={
                    "gender": pref.get("gender") or "",
                    "age_group": pref.get("ageGroup") or "",
                    "stay_scene": pref.get("stayScene") or "",
                    "bedtime": pref.get("bedtime") or "",
                    "wakeup": pref.get("wakeup") or "",
                    "preferred_temp": pref.get("preferredTemp"),
                    "preferred_humidity": pref.get("preferredHumidity"),
                    "light": pref.get("light") or "",
                    "sound": pref.get("sound") or "",
                    "pillow": pref.get("pillow") or "",
                    "mattress": pref.get("mattress") or "",
                    "issues": "、".join(ISSUE_LABEL.get(str(item), str(item)) for item in (pref.get("issues") or [])),
                    "fragrance": pref.get("fragrance") or "",
                    "bedtime_habit": pref.get("bedtimeHabit") or "",
                    "scene_name": scene_name,
                    "uploaded_at": now,
                },
            )
            GuestUpload.objects.create(
                kind="preference",
                guest_email=guest.email,
                room_id=guest.selected_room_id or "",
                summary=f"{guest.nickname} 上传偏好 · {scene_name or '已生成画像'}",
                payload_json=json.dumps({"stayScene": pref.get("stayScene"), "preferredTemp": pref.get("preferredTemp")}, ensure_ascii=False),
            )
        if guest.selected_room_id:
            guest.room_selected_at = now
            GuestUpload.objects.create(
                kind="select_room",
                guest_email=guest.email,
                room_id=guest.selected_room_id,
                summary=f"{guest.nickname} 确认选择 {guest.selected_room_id} 房",
                payload_json=json.dumps({"roomId": guest.selected_room_id}, ensure_ascii=False),
            )
        service_ids = list(GuestServiceChoice.objects.filter(guest_id=guest.email).values_list("service_id", flat=True))
        if service_ids:
            guest.services_at = now
            GuestUpload.objects.create(
                kind="services",
                guest_email=guest.email,
                room_id=guest.selected_room_id or "",
                summary=f"{guest.nickname} 提交 {len(service_ids)} 项酒店服务",
                payload_json=json.dumps({"serviceIds": service_ids}, ensure_ascii=False),
            )
        guest.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_guest_services_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('preference', '睡眠偏好'), ('select_room', '确认选房'), ('services', '酒店服务'), ('photo', '客房实景')], db_index=True, max_length=20, verbose_name='类型')),
                ('guest_email', models.CharField(blank=True, db_index=True, max_length=120, verbose_name='住客邮箱')),
                ('room_id', models.CharField(blank=True, db_index=True, max_length=8, verbose_name='房号')),
                ('summary', models.CharField(max_length=200, verbose_name='摘要')),
                ('payload_json', models.TextField(blank=True, verbose_name='明细 JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '上传流水',
                'verbose_name_plural': '上传流水',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': '住客提交', 'verbose_name_plural': '住客提交'},
        ),
        migrations.AddField(
            model_name='guest',
            name='gender',
            field=models.CharField(blank=True, max_length=20, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='guest',
            name='preference_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='偏好上传时间'),
        ),
        migrations.AddField(
            model_name='guest',
            name='room_selected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='选房时间'),
        ),
        migrations.AddField(
            model_name='guest',
            name='scene_title',
            field=models.CharField(blank=True, max_length=40, verbose_name='睡眠场景'),
        ),
        migrations.AddField(
            model_name='guest',
            name='services_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='服务提交时间'),
        ),
        migrations.AddField(
            model_name='guest',
            name='stay_scene',
            field=models.CharField(blank=True, max_length=20, verbose_name='入住场景'),
        ),
        migrations.AddField(
            model_name='room',
            name='photo_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='实景更新时间'),
        ),
        migrations.CreateModel(
            name='SleepPreferenceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(blank=True, choices=[('female', '女'), ('male', '男'), ('other', '不愿透露')], max_length=20, verbose_name='性别')),
                ('age_group', models.CharField(blank=True, choices=[('18-25', '18–25'), ('26-35', '26–35'), ('36-50', '36–50'), ('51+', '51 及以上')], max_length=20, verbose_name='年龄段')),
                ('stay_scene', models.CharField(blank=True, choices=[('business', '商务'), ('wellness', '康养'), ('family', '亲子'), ('leisure', '休闲')], max_length=20, verbose_name='入住场景')),
                ('bedtime', models.CharField(blank=True, max_length=8, verbose_name='就寝')),
                ('wakeup', models.CharField(blank=True, max_length=8, verbose_name='起床')),
                ('preferred_temp', models.FloatField(blank=True, null=True, verbose_name='偏好温度')),
                ('preferred_humidity', models.IntegerField(blank=True, null=True, verbose_name='偏好湿度')),
                ('light', models.CharField(blank=True, choices=[('dark', '全黑'), ('dim', '微光'), ('nightlight', '夜灯')], max_length=20, verbose_name='光线')),
                ('sound', models.CharField(blank=True, choices=[('silent', '绝对安静'), ('white-noise', '白噪音'), ('soft-music', '轻音乐')], max_length=20, verbose_name='声音')),
                ('pillow', models.CharField(blank=True, choices=[('soft', '软'), ('medium', '适中'), ('firm', '硬')], max_length=20, verbose_name='枕头')),
                ('mattress', models.CharField(blank=True, choices=[('soft', '软'), ('medium', '适中'), ('firm', '硬')], max_length=20, verbose_name='床垫')),
                ('issues', models.CharField(blank=True, max_length=120, verbose_name='睡眠问题')),
                ('fragrance', models.CharField(blank=True, max_length=80, verbose_name='香氛')),
                ('bedtime_habit', models.CharField(blank=True, max_length=200, verbose_name='睡前习惯')),
                ('scene_name', models.CharField(blank=True, max_length=40, verbose_name='生成场景')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True, verbose_name='上传时间')),
                ('guest', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pref_record', to='hotel.guest', verbose_name='住客')),
            ],
            options={
                'verbose_name': '睡眠偏好',
                'verbose_name_plural': '睡眠偏好',
            },
        ),
        migrations.RunPython(backfill_intake, noop),
    ]
