# Generated by Django 5.1.7 on 2026-09-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_guest_intake_records'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestAccount',
            fields=[
            ],
            options={
                'verbose_name': '客户账号',
                'verbose_name_plural': '客户账号',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hotel.account',),
        ),
        migrations.CreateModel(
            name='ManagerAccount',
            fields=[
            ],
            options={
                'verbose_name': '酒店管理员账号',
                'verbose_name_plural': '酒店管理员账号',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('hotel.account',),
        ),
    ]
