# Generated by Django 5.1.7 on 2026-09-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_account_role_proxies'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestStay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_email', models.CharField(max_length=120, unique=True, verbose_name='客户邮箱')),
                ('nickname', models.CharField(max_length=80, verbose_name='客户')),
                ('room_id', models.CharField(max_length=8, verbose_name='所选房间')),
                ('status', models.CharField(choices=[('checked_in', '已入住'), ('checked_out', '已退房')], db_index=True, default='checked_in', max_length=20, verbose_name='入住状态')),
                ('selected_at', models.DateTimeField(blank=True, null=True, verbose_name='选房时间')),
                ('checked_out_at', models.DateTimeField(blank=True, null=True, verbose_name='退房时间')),
            ],
            options={
                'verbose_name': '客户选房',
                'verbose_name_plural': '客户选房',
                'ordering': ['status', 'room_id'],
            },
        ),
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name': '住户偏好', 'verbose_name_plural': '住户偏好'},
        ),
    ]
