# Generated by Django 5.1.7 on 2026-09-05 11:14

import json

from django.db import migrations, models


ISSUE_LABEL = {
    "insomnia": "失眠",
    "light-sleeper": "易醒",
    "snoring": "打鼾",
    "allergy": "过敏",
}


def fill_form_fields(apps, schema_editor):
    Guest = apps.get_model("hotel", "Guest")
    for guest in Guest.objects.all():
        if not guest.preference_json:
            continue
        try:
            pref = json.loads(guest.preference_json)
        except json.JSONDecodeError:
            continue
        issues = pref.get("issues") or []
        guest.gender = pref.get("gender") or guest.gender
        guest.age_group = pref.get("ageGroup") or ""
        guest.stay_scene = pref.get("stayScene") or guest.stay_scene
        guest.bedtime = pref.get("bedtime") or ""
        guest.wakeup = pref.get("wakeup") or ""
        guest.preferred_temp = pref.get("preferredTemp")
        guest.preferred_humidity = pref.get("preferredHumidity")
        guest.light = pref.get("light") or ""
        guest.sound = pref.get("sound") or ""
        guest.pillow = pref.get("pillow") or ""
        guest.mattress = pref.get("mattress") or ""
        guest.issues = "、".join(ISSUE_LABEL.get(str(item), str(item)) for item in issues)
        guest.fragrance = pref.get("fragrance") or ""
        guest.bedtime_habit = pref.get("bedtimeHabit") or ""
        guest.nickname = pref.get("nickname") or guest.nickname
        guest.save()


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_guest_stay'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='age_group',
            field=models.CharField(blank=True, choices=[('18-25', '18–25'), ('26-35', '26–35'), ('36-50', '36–50'), ('51+', '51 及以上')], max_length=20, verbose_name='年龄段'),
        ),
        migrations.AddField(
            model_name='guest',
            name='bedtime',
            field=models.CharField(blank=True, max_length=8, verbose_name='就寝时间'),
        ),
        migrations.AddField(
            model_name='guest',
            name='bedtime_habit',
            field=models.CharField(blank=True, max_length=200, verbose_name='睡前习惯'),
        ),
        migrations.AddField(
            model_name='guest',
            name='fragrance',
            field=models.CharField(blank=True, max_length=80, verbose_name='香氛'),
        ),
        migrations.AddField(
            model_name='guest',
            name='issues',
            field=models.CharField(blank=True, max_length=120, verbose_name='睡眠问题'),
        ),
        migrations.AddField(
            model_name='guest',
            name='light',
            field=models.CharField(blank=True, choices=[('dark', '全黑'), ('dim', '微光'), ('nightlight', '夜灯')], max_length=20, verbose_name='光线'),
        ),
        migrations.AddField(
            model_name='guest',
            name='mattress',
            field=models.CharField(blank=True, choices=[('soft', '软'), ('medium', '适中'), ('firm', '硬')], max_length=20, verbose_name='床垫软硬'),
        ),
        migrations.AddField(
            model_name='guest',
            name='pillow',
            field=models.CharField(blank=True, choices=[('soft', '软'), ('medium', '适中'), ('firm', '硬')], max_length=20, verbose_name='枕头硬度'),
        ),
        migrations.AddField(
            model_name='guest',
            name='preferred_humidity',
            field=models.IntegerField(blank=True, null=True, verbose_name='偏好湿度'),
        ),
        migrations.AddField(
            model_name='guest',
            name='preferred_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='偏好温度'),
        ),
        migrations.AddField(
            model_name='guest',
            name='sound',
            field=models.CharField(blank=True, choices=[('silent', '绝对安静'), ('white-noise', '白噪音'), ('soft-music', '轻音乐')], max_length=20, verbose_name='声音'),
        ),
        migrations.AddField(
            model_name='guest',
            name='wakeup',
            field=models.CharField(blank=True, max_length=8, verbose_name='起床时间'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='email',
            field=models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='提交账号'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='gender',
            field=models.CharField(blank=True, choices=[('female', '女'), ('male', '男'), ('other', '不愿透露')], max_length=20, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='preference_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='确认上传时间'),
        ),
        migrations.AlterField(
            model_name='guest',
            name='stay_scene',
            field=models.CharField(blank=True, choices=[('business', '商务'), ('wellness', '康养'), ('family', '亲子'), ('leisure', '休闲')], max_length=20, verbose_name='入住场景'),
        ),
        migrations.RunPython(fill_form_fields, noop),
    ]
